name: weverse-backend

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.IP}}
          username: ${{secrets.ID}}
          key: ${{secrets.KEY}}
          port: ${{secrets.PORT}}
          script: |
            cd weverse-backend
            git pull
            npm install
            npm run build
            npm run pm2:reload
            npm run slack ${{ github.event.head_commit.message }}
            npm run slack '${{ github.event.head_commit.message }}'
